FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Vite en Docker necesita --host para permitir el acceso externo
CMD ["npm", "run", "dev", "--", "--host"]
