-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table
create table if not exists users (
  id uuid default uuid_generate_v4() primary key,
  username text unique not null,
  password text not null,
  current_session_id text,
  is_session_active boolean default false,
  last_seen timestamp with time zone,
  role text default 'user',
  created_at timestamp with time zone default now()
);

-- Products Table
create table if not exists products (
  id uuid default uuid_generate_v4() primary key,
  barcode text,
  code text unique, -- Used for lookup by internal code
  description text,
  created_at timestamp with time zone default now()
);

-- Pre-Remitos (Orders coming from external system)
create table if not exists pre_remitos (
  id uuid default uuid_generate_v4() primary key,
  order_number text unique not null,
  items jsonb, -- Stores array of items
  status text default 'pending',
  created_at timestamp with time zone default now()
);

-- Pedidos Ventas (Supplemental info for Pre-Remitos)
-- This table references pre_remitos so we can join them.
-- We assume one PV per Pre-Remito for simplicity, or 1:1 relationship.
create table if not exists pedidos_ventas (
  id uuid default uuid_generate_v4() primary key,
  order_number text references pre_remitos(order_number) on delete cascade,
  numero_pv text,
  sucursal text,
  created_at timestamp with time zone default now()
);

-- Remitos (Processed Orders)
create table if not exists remitos (
  id uuid default uuid_generate_v4() primary key,
  remito_number text,
  items jsonb,
  discrepancies jsonb,
  clarification text,
  status text default 'processed',
  created_by text,
  date timestamp with time zone default now()
);

-- Optional: Create a dummy admin user (Recommended to change password immediately)
-- Password is 'admin123' hashed (example hash, might need to be generated by app to be valid bcrypt)
-- insert into users (username, password, role) values ('admin', '$2a$10$YourHashedPasswordHere', 'admin') on conflict do nothing;
